// <auto-generated />
namespace WikiSurfCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class wikisession_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wikisession_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202102130218386_wikisession_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
